heat_template_version: 2021-04-16
description: "Lab3 with PostgreSQL and Kafka installation"

resources:
  tpb-group:
    type: "OS::Neutron::SecurityGroup"
    properties:
      description: "Security group for app, db and kafka"
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: "0.0.0.0/0"
        - protocol: tcp
          port_range_min: 5432
          port_range_max: 5432
          remote_ip_prefix: "0.0.0.0/0"
        - protocol: tcp
          port_range_min: 9092 # Kafka
          port_range_max: 9092
          remote_ip_prefix: "0.0.0.0/0"

  tpb-server:
    type: "OS::Nova::Server"
    properties:
      name: "cherdantsev-instance-lab03"
      flavor: "m1.small"
      image: "16729277-5d18-44ce-9581-1b2fd5d5659a"
      key_name: "cherdantsev"
      networks:
        - port: { get_resource: server-01-port }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        # 1. Установка PostgreSQL
        apt-get update
        apt-get install -y postgresql postgresql-contrib

        systemctl start postgresql
        systemctl enable postgresql

        # Настройка БД (пароль '123' и база 'weather_bot')
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '123';"
        sudo -u postgres psql -c "CREATE DATABASE weather_bot;"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE weather_bot TO postgres;"

        # 2. Установка Java (нужна для Kafka)
        apt-get install openjdk-21-jre-headless -y

        # 3. Установка Kafka
        cd /home/ubuntu
        wget https://archive.apache.org/dist/kafka/3.6.0/kafka_2.13-3.6.0.tgz
        tar -xzf kafka_2.13-3.6.0.tgz
        mv kafka_2.13-3.6.0 /opt/kafka

        # Запуск Zookeeper
        /opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
        # Запуск Kafka
        /opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties

    depends_on:
      - tpb-group

  server-01-port:
    type: OS::Neutron::Port
    properties:
      network_id: "6a69f855-8a2d-4994-baf0-ed4feedd897b" # students.net ID
      security_groups:
        - default
        - { get_resource: tpb-group }