- name: Infrastructure and Configuration
  hosts: localhost
  connection: local
  tasks:
    - name: Run terraform
      environment:
        TF_VAR_user_name: "{{ lookup('env', 'OS_USERNAME') }}"
        TF_VAR_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      terraform:
        project_path: "./terraform-openstack"
        state: present
      register: trfrm

    - name: Add host to inventory
      add_host:
        name: "new_server"
        ansible_host: "{{ trfrm.outputs.server_ip.value }}"
        ansible_user: ubuntu
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        groups: tpb_servers

- name: Configure Server
  hosts: tpb_servers
  become: yes
  tasks:
    - name: Update apt and install base soft
      apt:
        update_cache: yes
        name: 
          - postgresql
          - python3-psycopg2
          - openjdk-21-jre-headless
          - acl
        state: present

    - name: Setup Postgres Database
      become_user: postgres
      block:
        - name: Set postgres password
          community.postgresql.postgresql_user:
            name: postgres
            password: "123"
        - name: Create app database
          community.postgresql.postgresql_db:
            name: weather_bot

    - name: Install Kafka
      block:
        - name: Download Kafka
          get_url:
            url: https://archive.apache.org/dist/kafka/3.6.0/kafka_2.13-3.6.0.tgz
            dest: /tmp/kafka.tgz
        - name: Unpack Kafka
          unarchive:
            src: /tmp/kafka.tgz
            dest: /opt/
            remote_src: yes
        - name: Rename Kafka dir
          shell: mv /opt/kafka_2.13-3.6.0 /opt/kafka
          args:
            creates: /opt/kafka

    - name: Start Kafka and Zookeeper
      shell: |
        export KAFKA_HEAP_OPTS="-Xmx512M -Xms256M"
        /opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
        sleep 10
        /opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
      args:
        executable: /bin/bash

    - name: Deploy Service
      copy:
        src: botserver.service
        dest: /etc/systemd/system/weather-bot.service
    
    - name: Restart Bot Service
      systemd:
        name: weather-bot
        state: restarted
        daemon_reload: yes
        enabled: yes