- name: Infrastructure Creation
  hosts: localhost
  connection: local
  vars:
    terraform_rc_path: .terraformrc
    terraform_path: ./terraform-openstack
  tasks:
    - name: Prepare Terraform Mirror (set yandex mirror)
      copy:
        src: "{{ terraform_rc_path }}"
        dest: ~/.terraformrc

    - name: Run terraform
      environment:
        TF_VAR_user_name: "{{ lookup('env', 'OS_USERNAME') }}"
        TF_VAR_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      terraform:
        project_path: "{{ terraform_path }}"
        force_init: yes
        state: present
      register: trfrm

    - name: Add instance host to inventory
      add_host:
        name: "new_server"
        groups: tpb_servers
        ansible_host: "{{ trfrm.outputs.server_ip.value }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/devops_keypair
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ trfrm.outputs.server_ip.value }}"
        port: 22
        delay: 10
        timeout: 300

- name: Configure Server (DB, Kafka, Java, App)
  hosts: tpb_servers
  become: yes
  tasks:
    - name: Update apt and install base soft
      apt:
        update_cache: yes
        name: 
          - postgresql
          - python3-psycopg2
          - openjdk-21-jre-headless
          - acl
        state: present

    - name: Setup Postgres Database
      become_user: postgres
      block:
        - name: Set postgres password
          community.postgresql.postgresql_user:
            name: postgres
            password: "123"
        - name: Create app database
          community.postgresql.postgresql_db:
            name: weather_bot

    - name: Install Kafka
      block:
        - name: Download Kafka
          get_url:
            url: https://archive.apache.org/dist/kafka/3.6.0/kafka_2.13-3.6.0.tgz
            dest: /tmp/kafka.tgz
        - name: Unpack Kafka
          unarchive:
            src: /tmp/kafka.tgz
            dest: /opt/
            remote_src: yes
        - name: Rename Kafka dir
          shell: mv /opt/kafka_2.13-3.6.0 /opt/kafka
          args:
            creates: /opt/kafka

    - name: Start Kafka and Zookeeper
      shell: |
        export KAFKA_HEAP_OPTS="-Xmx512M -Xms256M"
        /opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
        sleep 15
        /opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
      args:
        executable: /bin/bash

    - name: Deploy Service
      copy:
        src: botserver.service
        dest: /etc/systemd/system/weather-bot.service
    
    - name: Restart Bot Service
      systemd:
        name: weather-bot
        state: restarted
        daemon_reload: yes
        enabled: yes