apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: cherdantsev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_DB
          value: "weather_bot"
        ports:
        - containerPort: 5432