apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheardantsev-bot
  namespace: cherdantsev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheardantsev-bot
  template:
    metadata:
      labels:
        app: cheardantsev-bot
    spec:
      containers:
      - name: bot
        image: artemis43rd/weather-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db:5432/weather_bot"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "localhost:9092"