apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheardantsev-bot
  namespace: cherdantsev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheardantsev-bot
  template:
    metadata:
      labels:
        app: cheardantsev-bot
    spec:
      containers:
      - name: bot
        image: artemis43rd/weather-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: BOT_HOST_HTTP_PORT
          value: "8081"
        - name: DB_URL
          value: "jdbc:postgresql://postgres-db:5432/weather_bot"
        - name: DB_USERNAME
          value: "postgres"
        - name: BOT_NAME
          value: "WeatherMasterBot"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: KAFKA_CONSUMER_GROUP_ID
          value: "weather-app-telegram-bot-group"

        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: OPENWEATHER_API_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cheardantsev-bot-service
  namespace: cherdantsev-ns
spec:
  type: NodePort
  selector:
    app: cheardantsev-bot
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bot-ingress
  namespace: cherdantsev-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cheardantsev-bot-service
            port:
              number: 8081